name=ACCController
version=1.0.0
author=BIBO
maintainer=BIBO
sentence=Simple acceleration profile controller for Arduino.
paragraph=Quadratic acceleration and deceleration speed profile controller.
category=Signal Input/Output
architectures=*