name=PIDController
version=1.0.0
author=BIBO
maintainer=BIBO
sentence=Simple PID controller for Arduino.
paragraph=PID controller with output and integral limits.
category=Signal Input/Output
architectures=*